par(mfrow = c(2, 2), mar = c(5, 4, 2, 1))
plot(my_dat$the_time, my_dat$Global_active_power, type="l", ylab="Global active power (killowatts)", cex=0.8, xlab="")
plot(my_dat$the_time, my_dat$Voltage, type="l", ylab="Voltage", xlab="")
plot(my_dat$the_time, my_dat$Sub_metering_1, type="l", ylab="Energy sub metering", xlab="")
lines(my_dat$the_time, my_dat$Sub_metering_2, type="l", lty=2, col="red")
lines(my_dat$the_time, my_dat$Sub_metering_3, type="l", lty=2, col="blue")
plot(my_dat$the_time, my_dat$Global_reactive_power, type="l", ylab="Global reactive power (killowatts)", cex=0.8, xlab="datetime")
dev.copy(png, file = "plot4.png")
dev.off()